"use strict";

const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { resolve } = require("node:path");

const html = readFileSync(resolve(__dirname, "../index.html"), "utf8");
const css = readFileSync(resolve(__dirname, "../styles.css"), "utf8");
const app = readFileSync(resolve(__dirname, "../app.js"), "utf8");

const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]);
assert.equal(new Set(ids).size, ids.length, "HTML IDs must be unique.");
assert.match(html, /<title>Energy and Temperature Change Simulation<\/title>/);
assert.match(html, /<header class="site-header">\s*<h1>Energy and Temperature Change Simulation<\/h1>\s*<\/header>/);
assert.match(html, /Part 1 · Direct heating/);
assert.match(html, /Part 2 · Energy transfer/);
assert.doesNotMatch(html, /Day 1|Day 2/);
assert.match(html, /role="tablist"/);
assert.equal((html.match(/role="tab"/g) || []).length, 2);
assert.equal((html.match(/role="tabpanel"/g) || []).length, 2);
assert.match(html, /aria-live="polite"/);
assert.match(html, /<th scope="col">/);
assert.match(html, /How should the solid be heated\?/);
assert.match(html, /Choose the energy added/);
assert.match(html, /Heat each solid to the same temperature/);
const heatingChoiceMarkup = html.match(/<div class="segmented heating-mode-choices">([\s\S]*?)<\/div>/)?.[1] || "";
assert.match(heatingChoiceMarkup, /value="target-temperature" checked/);
assert.doesNotMatch(heatingChoiceMarkup, /value="energy" checked/);
assert.ok(
  heatingChoiceMarkup.indexOf('value="target-temperature"') < heatingChoiceMarkup.indexOf('value="energy"'),
  "Target-temperature mode must be the first calorimetry heating choice."
);
assert.match(html, /Aluminum \(Specific heat = 0\.90 J\/\(g·°C\)\)/);
assert.match(html, /Copper \(Specific heat = 0\.385 J\/\(g·°C\)\)/);
assert.match(html, /Iron \(Specific heat = 0\.45 J\/\(g·°C\)\)/);
assert.match(html, /Granite \(Specific heat = 0\.79 J\/\(g·°C\)\)/);
assert.match(html, /id="solid-specific-heat-value"/);
assert.match(html, /id="immersed-specific-heat-value"/);
assert.match(app, /model\.SPECIFIC_HEAT_LABELS\[material\]/);
assert.match(html, /Energy added to the solid/);
assert.match(html, /Energy needed to heat the solid/);
assert.match(html, /id="target-solid-temperature"[^>]+value="90"/);
assert.match(html, /name="solid-energy" value="2090"/);
assert.match(html, /name="solid-energy" value="4180"/);
assert.match(html, /name="solid-energy" value="6270"/);
assert.match(html, /Initial water temp\. \(°C\)/);
assert.match(html, /Heating choice/);
assert.match(html, /Energy added or calculated \(J\)/);
assert.match(html, /Target solid temp\. \(°C\)/);
assert.match(html, /Solid temp\. before transfer \(°C\)/);
assert.match(app, /trial\.initialWaterTemperature\.toFixed\(1\)/);
assert.match(app, /trial\.solidTemperatureBeforeTransfer\.toFixed\(1\)/);
assert.match(app, /trial\.finalSolidTemperature\.toFixed\(1\)/);
assert.match(app, /trial\.finalWaterTemperature\.toFixed\(1\)/);
assert.doesNotMatch(html + app, /contains? (?:Q|heat)/i);
assert.doesNotMatch(html + app, /(?:heats|warms) faster|how quickly/i);
assert.doesNotMatch(html, /<canvas|<svg/i, "No graphs or decorative SVG should be used.");
assert.match(css, /min-height:\s*48px/);
assert.match(css, /:focus-visible/);
assert.match(css, /prefers-reduced-motion:\s*reduce/);
assert.match(css, /@media \(max-width:\s*820px\)/);
assert.match(app, /ArrowLeft/);
assert.match(app, /ArrowRight/);
assert.match(app, /motionQuery\.matches/);
assert.match(html, /id="skip-heating-animation"/);
assert.match(html, /id="skip-calorimetry-animation"/);
assert.match(html, /id="sample-visual"[\s\S]*class="thermometer"[\s\S]*id="heating-mercury"/);
assert.match(html, /id="solid-sample"[\s\S]*class="mini-thermometer"[\s\S]*id="solid-mercury"/);
assert.match(app, /updateHeatingMass/);
assert.match(app, /updateCalorimetryMass/);
assert.match(app, /updateWaterMass/);
assert.match(app, /\{ 200: "110px", 400: "135px", 800: "165px" \}/);
const waterHeights = [110, 135, 165];
const solidHeights = [44, 62, 87];
assert.ok(waterHeights[0] > Math.max(...solidHeights) + 10, "The minimum water depth must fully cover the largest solid.");
assert.ok(waterHeights[0] < waterHeights[1] && waterHeights[1] < waterHeights[2], "Water depth must increase with water mass.");
assert.match(css, /\.cup-label \{[^}]*top: 8px/s);
assert.match(css, /\.solid-specific-heat/);
assert.match(app, /updateCalorimetryHeatingChoice/);
assert.match(app, /energyChoiceField\.hidden = useTargetTemperature/);
assert.match(app, /targetTemperatureField\.hidden = !useTargetTemperature/);
assert.match(app, /control\.disabled = useTargetTemperature/);
assert.match(app, /targetSolidTemperature\.disabled = !useTargetTemperature/);
assert.match(app, /targetSolidTemperature\.value = "90"/);
assert.match(app, /input\[name="solid-energy"\]\[value="4180"\]/);
assert.match(app, /createCalorimetryHistoryRecord/);
assert.match(app, /The warmer solid transferred energy to the cooler water\. The solid cooled and the water warmed until they reached the same temperature\./);
assert.match(css, /\.mixed \.solid-sample \{ opacity: 0; visibility: hidden; \}/);
assert.match(app, /state\.heating\.trials/);
assert.match(app, /state\.calorimetry\.trials/);
assert.doesNotMatch(html + app, /\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/);
assert.doesNotMatch(html + app, /\b(?:localStorage|sessionStorage|indexedDB)\b/);
assert.doesNotMatch(html, /<(?:script|link|img)[^>]+(?:src|href)="https?:/i);
assert.match(html, /Model information — open when directed/);
assert.match(html, /Water: 4\.184 J\/\(g·°C\)/);
assert.match(html, /ideal model/i);
assert.match(html, /No energy is lost to the container or surroundings/);
assert.match(html, /class="calorimetry-history-table"/);

console.log("Static checks passed: two tabs, both calorimetry modes, complete history, student wording, privacy, responsive layout, keyboard hooks, and reduced-motion support.");
