(()=>{
  const {PROJECTS,simulate,projectCost}=window.WatershedModel;
  const canvas=document.querySelector('#watershed'),ctx=canvas.getContext('2d'),hydro=document.querySelector('#hydrograph'),hctx=hydro.getContext('2d');
  const state={projects:new Set(),trials:[],particles:[],animating:false,result:null};
  const inputs=['rainfall','impervious','slope'];
  const projectCopy={rainGardens:'Capture roof and parking-lot runoff.',trees:'Slow bankside flow and hold soil.',pavement:'Let water infiltrate where it lands.',wetland:'Store water and trap sediment.'};
  document.querySelector('#projects').innerHTML=Object.entries(PROJECTS).map(([k,p])=>`<label class="project-option"><input type="checkbox" value="${k}"><span><strong>${p.name}</strong><small>${projectCopy[k]}</small></span><span class="cost">${p.cost} credits</span></label>`).join('');
  function current(){return{rainfall:+document.querySelector('#rainfall').value,impervious:+document.querySelector('#impervious').value,slope:+document.querySelector('#slope').value,soil:document.querySelector('#soil').value,projects:[...state.projects]};}
  function labels(){inputs.forEach(id=>document.querySelector(`#${id}-value`).textContent=document.querySelector(`#${id}`).value+(id==='rainfall'?' mm/h':id==='impervious'?'%':'°'));}
  inputs.forEach(id=>document.querySelector(`#${id}`).addEventListener('input',()=>{labels();drawScene();}));document.querySelector('#soil').addEventListener('change',drawScene);
  document.querySelector('#projects').addEventListener('change',e=>{const next=new Set(state.projects);e.target.checked?next.add(e.target.value):next.delete(e.target.value);if(projectCost([...next])>100){e.target.checked=false;document.querySelector('#feedback').className='feedback error';document.querySelector('#feedback').textContent='That project exceeds the 100-credit budget. Remove another project first.';return;}state.projects=next;updateBudget();drawScene();});
  function updateBudget(){document.querySelector('#budget').textContent=`Budget remaining: ${100-projectCost([...state.projects])} credits`;}
  function drawScene(){
    const w=canvas.width,h=canvas.height,c=current();ctx.clearRect(0,0,w,h);
    const sky=ctx.createLinearGradient(0,0,0,h*.5);sky.addColorStop(0,'#a8dbf0');sky.addColorStop(1,'#edf7fb');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
    ctx.beginPath();ctx.moveTo(0,h*.48);ctx.quadraticCurveTo(w*.22,h*.18,w*.46,h*.58);ctx.quadraticCurveTo(w*.7,h*.3,w,h*.52);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fillStyle='#72a85b';ctx.fill();
    ctx.beginPath();ctx.moveTo(0,h*.7);ctx.quadraticCurveTo(w*.45,h*.62,w,h*.68);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fillStyle='#558c48';ctx.fill();
    ctx.beginPath();ctx.moveTo(w*.42,h*.52);ctx.bezierCurveTo(w*.5,h*.65,w*.53,h*.82,w*.64,h);ctx.lineTo(w*.8,h);ctx.bezierCurveTo(w*.65,h*.78,w*.62,h*.61,w*.56,h*.49);ctx.strokeStyle='#3f9fc5';ctx.lineWidth=24;ctx.stroke();
    const houses=Math.round(c.impervious/12);for(let i=0;i<houses;i++){const x=80+i*78,y=h*.55+(i%2)*38;ctx.fillStyle='#d8d5cd';ctx.fillRect(x,y,48,35);ctx.fillStyle='#7a4e3a';ctx.beginPath();ctx.moveTo(x-5,y);ctx.lineTo(x+24,y-20);ctx.lineTo(x+53,y);ctx.fill();}
    if(state.projects.has('trees'))for(let i=0;i<8;i++)tree(w*.47+i*25,h*.64+i*8);
    if(state.projects.has('rainGardens'))badge(w*.18,h*.62,'Rain gardens');if(state.projects.has('pavement'))badge(w*.12,h*.82,'Permeable');if(state.projects.has('wetland'))badge(w*.72,h*.72,'Wetland');
    for(const p of state.particles){ctx.beginPath();ctx.arc(p.x,p.y,p.sediment?4:3,0,Math.PI*2);ctx.fillStyle=p.sediment?'#9c6644':'#2b9ed1';ctx.fill();}
    ctx.fillStyle='#17322a';ctx.font='700 15px system-ui';ctx.fillText(`Slope ${c.slope}°`,18,30);ctx.fillText('Stream gauge ▼',w*.69,h*.92);
  }
  function tree(x,y){ctx.fillStyle='#6b4423';ctx.fillRect(x-3,y,6,20);ctx.beginPath();ctx.arc(x,y-6,12,0,Math.PI*2);ctx.fillStyle='#236b42';ctx.fill();}
  function badge(x,y,t){ctx.fillStyle='#ffd100';ctx.fillRect(x-5,y-18,ctx.measureText(t).width+18,24);ctx.fillStyle='#17322a';ctx.font='700 13px system-ui';ctx.fillText(t,x,y);}
  function animateStorm(result){state.animating=true;state.particles=Array.from({length:70},(_,i)=>({x:(i*97)%canvas.width,y:-((i*53)%420),vx:1.1+(i%4)*.3,vy:4+(i%5)*.5,sediment:i%5===0}));let frame=0;function tick(){frame++;for(const p of state.particles){p.y+=p.vy;p.x+=p.x<canvas.width*.52?p.vx:-p.vx*.4;if(p.y>canvas.height){p.y=-10;p.x=(p.x*1.7)%canvas.width;}}drawScene();if(frame<90&&!matchMedia('(prefers-reduced-motion: reduce)').matches)requestAnimationFrame(tick);else{state.animating=false;state.particles=[];drawScene();document.querySelector('#storm-state').textContent='Complete';}}requestAnimationFrame(tick);}
  function drawHydro(values){const w=hydro.width,h=hydro.height;hctx.clearRect(0,0,w,h);hctx.fillStyle='#f8fbfa';hctx.fillRect(0,0,w,h);hctx.strokeStyle='#9ab3a7';hctx.beginPath();hctx.moveTo(42,15);hctx.lineTo(42,h-32);hctx.lineTo(w-14,h-32);hctx.stroke();const max=Math.max(70,...values);hctx.beginPath();values.forEach((v,i)=>{const x=42+i*(w-62)/(values.length-1),y=h-32-v/max*(h-55);i?hctx.lineTo(x,y):hctx.moveTo(x,y);});hctx.strokeStyle='#1877a8';hctx.lineWidth=4;hctx.stroke();hctx.fillStyle='#17322a';hctx.font='14px system-ui';hctx.fillText('Flow',5,22);hctx.fillText('Time →',w-65,h-8);}
  document.querySelector('#run-storm').addEventListener('click',()=>{if(state.animating)return;const c=current(),r=simulate(c);state.result=r;state.trials.push({input:c,result:r});['runoff','peak','infiltration'].forEach(k=>document.querySelector(`#${k}`).textContent=r[k]);document.querySelector('#sediment-result').textContent=r.sediment;drawHydro(r.hydrograph);animateStorm(r);renderHistory();const f=document.querySelector('#feedback');if(r.success){f.className='feedback success';f.textContent='Design target met: both peak flow and sediment are below the limits.';}else{f.className='feedback error';const misses=[];if(r.peak>=58)misses.push('peak flow');if(r.sediment>=35)misses.push('sediment');f.textContent=`Target not yet met. Revise the design to lower ${misses.join(' and ')}.`;}});
  function renderHistory(){document.querySelector('#history-body').innerHTML=state.trials.map((t,i)=>`<tr><td>${i+1}</td><td>${t.input.projects.map(k=>PROJECTS[k].name).join(', ')||'Baseline'}</td><td>${t.result.runoff}</td><td>${t.result.peak}</td><td>${t.result.sediment}</td><td>${t.result.success?'Target met':'Revise'}</td></tr>`).join('');}
  document.querySelector('#reset-design').addEventListener('click',()=>{state.projects.clear();document.querySelectorAll('#projects input').forEach(i=>i.checked=false);updateBudget();drawScene();});
  document.querySelector('#clear-history').addEventListener('click',()=>{state.trials=[];renderHistory();});
  document.querySelector('#download').addEventListener('click',()=>{if(!state.trials.length){document.querySelector('#feedback').textContent='Run at least one trial before downloading a summary.';return;}const lines=['Watershed Under Pressure — Investigation Summary','',...state.trials.map((t,i)=>`Trial ${i+1}: ${t.input.projects.map(k=>PROJECTS[k].name).join(', ')||'Baseline'} | runoff ${t.result.runoff} | peak ${t.result.peak} | sediment ${t.result.sediment} | ${t.result.success?'target met':'revise'}`),'',`Recommendation: ${document.querySelector('#claim').value||'(not entered)'}`,'','This classroom model is not a site-specific flood forecast.'];const blob=new Blob([lines.join('\n')],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='watershed-investigation.txt';a.click();URL.revokeObjectURL(a.href);});
  function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(620,Math.round(rect.width*dpr));canvas.height=Math.round(Math.max(360,rect.width*.61)*dpr);drawScene();}new ResizeObserver(resize).observe(canvas);labels();updateBudget();drawScene();drawHydro([0,0]);
})();
