(()=>{
  const {SUBSTANCES,readings,boilingPoint,meltingPoint}=window.MatterModel;
  const pcanvas=document.querySelector('#particles'),pctx=pcanvas.getContext('2d'),map=document.querySelector('#phase-map'),mctx=map.getContext('2d');
  const state={trials:[],particles:Array.from({length:42},(_,i)=>({x:40+(i%7)*70,y:45+Math.floor(i/7)*55,vx:(i%3-1)*.5,vy:((i*7)%3-1)*.45})),last:0};
  function values(){return{key:document.querySelector('#substance').value,temp:+document.querySelector('#temperature').value,pressure:+document.querySelector('#pressure').value};}
  function update(){const v=values(),r=readings(v.key,v.temp,v.pressure);document.querySelector('#temperature-value').textContent=`${v.temp} °C`;document.querySelector('#pressure-value').textContent=`${v.pressure.toFixed(1)} atm`;document.querySelector('#phase-badge').textContent=r.phase[0].toUpperCase()+r.phase.slice(1);document.querySelector('#kinetic').textContent=r.kinetic.toFixed(2);document.querySelector('#spacing').textContent=r.spacing;document.querySelector('#boiling').textContent=`${r.boiling} °C`;updateMacro(r,v);drawMap(v);return r;}
  function updateMacro(r,v){const sample=document.querySelector('#sample'),piston=document.querySelector('#piston'),thermo=document.querySelector('#thermometer');piston.style.top=`${10+(v.pressure-0.5)/2.5*70}px`;thermo.style.height=`${Math.max(4,Math.min(96,(v.temp+220)/400*100))}%`;sample.style.background=SUBSTANCES[v.key].color+'aa';if(r.phase==='solid'){sample.style.height='35%';sample.style.left='18%';sample.style.right='18%';sample.style.borderRadius='10px 10px 0 0';document.querySelector('#observation').textContent='The sample keeps a definite shape and volume.';}else if(r.phase==='liquid'){sample.style.height='48%';sample.style.left='0';sample.style.right='0';sample.style.borderRadius='0';document.querySelector('#observation').textContent='The sample keeps its volume but takes the container’s shape.';}else{sample.style.height='100%';sample.style.left='0';sample.style.right='0';sample.style.opacity='.26';document.querySelector('#observation').textContent='The sample expands to fill the available container volume.';}if(r.phase!=='gas')sample.style.opacity='1';}
  function animate(t){const v=values(),r=readings(v.key,v.temp,v.pressure),speed=.3+r.kinetic*1.5;drawParticles(r,v,speed);requestAnimationFrame(animate);}requestAnimationFrame(animate);
  function drawParticles(r,v,speed){const w=pcanvas.width,h=pcanvas.height;pctx.clearRect(0,0,w,h);const grad=pctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#102b38');grad.addColorStop(1,'#061820');pctx.fillStyle=grad;pctx.fillRect(0,0,w,h);for(let i=0;i<state.particles.length;i++){const p=state.particles[i];if(r.phase==='solid'){const col=i%7,row=Math.floor(i/7),tx=75+col*(w-150)/6,ty=90+row*(h-180)/5;p.x+=(tx-p.x)*.08;p.y+=(ty-p.y)*.08;p.x+=Math.sin(performance.now()/100+i)*.18*r.kinetic;}else{p.x+=p.vx*speed*(r.phase==='gas'?2.4:1);p.y+=p.vy*speed*(r.phase==='gas'?2.4:1);if(r.phase==='liquid')p.y+=(h*.68-p.y)*.025;if(p.x<18||p.x>w-18)p.vx*=-1;if(p.y<18||p.y>h-18)p.vy*=-1;p.x=Math.max(18,Math.min(w-18,p.x));p.y=Math.max(18,Math.min(h-18,p.y));}pctx.beginPath();pctx.arc(p.x,p.y,r.phase==='gas'?9:13,0,Math.PI*2);pctx.fillStyle=SUBSTANCES[v.key].color;pctx.fill();pctx.strokeStyle='rgba(255,255,255,.65)';pctx.stroke();}pctx.fillStyle='white';pctx.font='700 16px system-ui';pctx.fillText(`${r.phase.toUpperCase()} · ${v.temp} °C · ${v.pressure.toFixed(1)} atm`,18,28);}
  function drawMap(v){const w=map.width,h=map.height;mctx.clearRect(0,0,w,h);const pad=45;mctx.fillStyle='#f8fbfa';mctx.fillRect(0,0,w,h);const s=SUBSTANCES[v.key];const x=t=>pad+(t+230)/430*(w-pad-18),y=p=>h-pad-(p-.5)/2.5*(h-pad-18);const melt=meltingPoint(v.key,1);mctx.fillStyle='#cde4f4';mctx.fillRect(pad,18,Math.max(1,x(melt)-pad),h-pad-18);mctx.fillStyle='#d9f0dc';mctx.fillRect(x(melt),18,Math.max(1,x(boilingPoint(v.key,3))-x(melt)),h-pad-18);mctx.fillStyle='#f7e0b5';mctx.fillRect(x(boilingPoint(v.key,.5)),18,w-18-x(boilingPoint(v.key,.5)),h-pad-18);mctx.strokeStyle='#17322a';mctx.beginPath();mctx.moveTo(pad,18);mctx.lineTo(pad,h-pad);mctx.lineTo(w-18,h-pad);mctx.stroke();mctx.beginPath();for(let p=.5;p<=3;p+=.1){const px=x(boilingPoint(v.key,p)),py=y(p);p===.5?mctx.moveTo(px,py):mctx.lineTo(px,py);}mctx.strokeStyle='#b13a32';mctx.lineWidth=3;mctx.stroke();mctx.beginPath();mctx.arc(x(v.temp),y(v.pressure),7,0,Math.PI*2);mctx.fillStyle='#005530';mctx.fill();mctx.fillStyle='#17322a';mctx.font='700 14px system-ui';mctx.fillText('solid',pad+12,38);mctx.fillText('liquid',x(melt)+12,38);mctx.fillText('gas',w-55,38);mctx.fillText('Temperature →',w-120,h-10);mctx.save();mctx.translate(14,h/2+35);mctx.rotate(-Math.PI/2);mctx.fillText('Pressure (atm)',0,0);mctx.restore();}
  ['substance','temperature','pressure'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',update));
  document.querySelector('#run-trial').addEventListener('click',()=>{const pred=document.querySelector('input[name="prediction"]:checked')?.value,feedback=document.querySelector('#feedback');if(!pred){feedback.className='feedback error';feedback.textContent='Choose a prediction before running the trial.';return;}const v=values(),r=update();state.trials.push({...v,prediction:pred,phase:r.phase});feedback.className='feedback '+(pred===r.phase?'success':'');feedback.textContent=pred===r.phase?'Prediction supported. Compare the particle and observable views.':`The model shows ${r.phase}. Use the particle spacing and phase map to revise your thinking.`;renderTrials();});
  function renderTrials(){document.querySelector('#trial-count').textContent=`${state.trials.length} trial${state.trials.length===1?'':'s'} recorded`;document.querySelector('#trials').innerHTML=state.trials.map(t=>`<tr><td>${SUBSTANCES[t.key].name}</td><td>${t.temp} °C</td><td>${t.pressure.toFixed(1)} atm</td><td>${t.prediction}</td><td>${t.phase}</td></tr>`).join('');}
  document.querySelector('#check-mystery').addEventListener('click',()=>{const ok=document.querySelector('#mystery').value==='ethanol',f=document.querySelector('#mystery-feedback');f.className='feedback '+(ok?'success':'error');f.textContent=ok?'Correct. Both phase-change temperatures match ethanol at 1 atm.':'Not yet. Compare both the melting point and boiling point, not just one value.';});
  document.querySelector('#clear').addEventListener('click',()=>{state.trials=[];renderTrials();});
  document.querySelector('#download').addEventListener('click',()=>{if(!state.trials.length)return;const rows=['Substance,Temperature_C,Pressure_atm,Prediction,Observed_phase',...state.trials.map(t=>`${SUBSTANCES[t.key].name},${t.temp},${t.pressure},${t.prediction},${t.phase}`)];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='matter-trials.csv';a.click();URL.revokeObjectURL(a.href);});
  function resize(){const rect=pcanvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);pcanvas.width=Math.max(450,Math.round(rect.width*dpr));pcanvas.height=Math.round(Math.max(340,rect.width*.72)*dpr);}new ResizeObserver(resize).observe(pcanvas);update();renderTrials();
})();
